[package]
name = "cwa_reader_rs"
version = "0.5.0"
edition = "2021"
license = "MIT"
exclude = ["tests/**"]

[lib]
name = "cwa_reader_rs"
crate-type = ["cdylib"]

[dependencies]
cwa-core = { version = "0.5.0", path = "../crates/cwa-core" }
pyo3 = { version = "0.26", features = ["extension-module"] }
numpy = "0.26"
